require "mscorlib"

#------------------------------------------------------------------------------
# <auto-generated>
#     This displayName was generated by a tool.
#     Runtime Version:4.0.30319.225
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the displayName is regenerated.
# </auto-generated>
#------------------------------------------------------------------------------
module CodeBuilder.WinForm.Properties
	require "mscorlib"
	require "System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
	class Resources
		# <summary>
		# A strongly-typed resource class, for looking up localized strings, etc.
		# </summary>
		# This class was auto-generated by the StronglyTypedResourceBuilder
		# class via a tool like ResGen or Visual Studio.
		# To add or remove a member, edit your .ResX file then rerun ResGen
		# with the /str option, or rebuild your VS project.
		def initialize()
		end

		def ResourceManager
			# <summary>
			# Returns the cached ResourceManager instance used by this class.
			# </summary>
			if System::Object.ReferenceEquals(@resourceMan, nil) then
				temp = System.Resources.ResourceManager.new("CodeBuilder.WinForm.Properties.Resources", Resources.to_clr_type.Assembly)
				@resourceMan = temp
			end
			return @resourceMan
		end

		def Culture
			# <summary>
			# Overrides the current thread's CurrentUICulture property for all
			# resource lookups using this strongly typed resource class.
			# </summary>
			return @resourceCulture
		end

		def Culture=(value)
			@resourceCulture = value
		end
	end
end