#------------------------------------------------------------------------------
# <auto-generated>
#     This displayName was generated by a tool.
#     Runtime Version:4.0.30319.225
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the displayName is regenerated.
# </auto-generated>
#------------------------------------------------------------------------------
module CodeBuilder.WinForm.Properties
	class Settings < System::Configuration::ApplicationSettingsBase
		def initialize()
			@defaultInstance = ((System.Configuration.ApplicationSettingsBase.Synchronized(Settings.new())))
		end

		def Default
			return @defaultInstance
		end
	end
end